import type { ServiceDescriptor } from "@/app/dashboard/components/ServiceCard";

export const SERVICES: ServiceDescriptor[] = [
  {
    id: "S-01",
    name: "Cloud Security Landing Zone",
    category: "Launch",
    description: "Zero-trust org baseline, SCPs, account vending for AWS, Azure, GCP.",
    status: "ACTIVE",
    ariaIntegration: "Low",
    coverage: 92,
  },
  {
    id: "S-02",
    name: "Secure Baseline Deployment",
    category: "Launch",
    description: "CIS benchmark automation and Config conformance packs.",
    status: "ACTIVE",
    ariaIntegration: "Medium",
    coverage: 88,
  },
  {
    id: "S-03",
    name: "Identity Foundation (SSO / MFA / IdP)",
    category: "Launch",
    description: "JIT-tiered access with Auto and Operator claims on every call.",
    status: "ACTIVE",
    ariaIntegration: "Medium",
    coverage: 95,
  },
  {
    id: "S-04",
    name: "Encryption & Key Management",
    category: "Launch",
    description: "KMS/HSM bootstrap, envelope encryption, key rotation policy.",
    status: "ACTIVE",
    ariaIntegration: "Low",
    coverage: 90,
  },
  {
    id: "S-05",
    name: "Cloud-Native Pentesting",
    category: "Red Team",
    description: "Attack Graph–driven exploit paths with manual red team validation.",
    status: "ACTIVE",
    ariaIntegration: "Medium",
    coverage: 78,
    href: "/dashboard/attack-graph",
  },
  {
    id: "S-06",
    name: "Adversary Simulation / BAS",
    category: "Red Team",
    description: "Autonomous attack-path scoring via BFS over the AGE graph.",
    status: "ACTIVE",
    ariaIntegration: "Core",
    coverage: 85,
  },
  {
    id: "S-07",
    name: "Purple Team Exercises",
    category: "Red Team",
    description: "ReAct trace replay from the incident knowledge base.",
    status: "PARTIAL",
    ariaIntegration: "High",
    coverage: 62,
  },
  {
    id: "S-08",
    name: "Phishing & Social Engineering Sim",
    category: "Red Team",
    description: "Correlated to identity anomaly signals via the CIEM layer.",
    status: "PLANNED",
    ariaIntegration: "Medium",
    coverage: 25,
  },
  {
    id: "S-09",
    name: "CSPM — Cloud Security Posture",
    category: "Internal",
    description: "Continuous posture monitoring with auto-remediation of drift.",
    status: "ACTIVE",
    ariaIntegration: "Core",
    coverage: 96,
    href: "/dashboard",
  },
  {
    id: "S-10",
    name: "DSPM — Data Security Posture",
    category: "Internal",
    description: "Data classifier output feeds ARIA SHAP features.",
    status: "ACTIVE",
    ariaIntegration: "High",
    coverage: 80,
  },
  {
    id: "S-11",
    name: "CNAPP — Cloud-Native App Protection",
    category: "Internal",
    description: "Runtime signals routed into the ARIA predictor.",
    status: "ACTIVE",
    ariaIntegration: "High",
    coverage: 82,
  },
  {
    id: "S-12",
    name: "CIEM — Entitlement Management",
    category: "Internal",
    description: "Least-privilege IAM recommendations and graph-based blast radius.",
    status: "ACTIVE",
    ariaIntegration: "High",
    coverage: 84,
  },
  {
    id: "S-13",
    name: "Vulnerability Management",
    category: "Internal",
    description: "KEV cross-reference, CVSS scoring, remediation orchestration.",
    status: "ACTIVE",
    ariaIntegration: "Medium",
    coverage: 89,
  },
  {
    id: "S-14",
    name: "Container & Kubernetes Security",
    category: "Internal",
    description: "Admission control and pod-level ARIA signals.",
    status: "ACTIVE",
    ariaIntegration: "Medium",
    coverage: 76,
  },
  {
    id: "S-15",
    name: "Configuration Drift & CIS Benchmarking",
    category: "Internal",
    description: "Continuous validation loop over CIS controls.",
    status: "ACTIVE",
    ariaIntegration: "Medium",
    coverage: 91,
  },
  {
    id: "S-16",
    name: "Generative AI Security",
    category: "Advanced",
    description: "Bedrock Guardrails, prompt-injection block, LLM anomaly detection.",
    status: "ACTIVE",
    ariaIntegration: "Core",
    coverage: 70,
  },
  {
    id: "S-17",
    name: "DevSecOps Automation",
    category: "Advanced",
    description: "IaC policy-as-code, CI/CD JIT tokens, shift-left auto-remediation.",
    status: "ACTIVE",
    ariaIntegration: "Core",
    coverage: 74,
  },
  {
    id: "S-18",
    name: "Incident Response & Forensics",
    category: "Advanced",
    description: "Sub-60s RCA with ReAct trace, immutable audit chain.",
    status: "ACTIVE",
    ariaIntegration: "Core",
    coverage: 88,
    href: "/dashboard/aria",
  },
  {
    id: "S-19",
    name: "FinOps Security Governance",
    category: "Advanced",
    description: "Zombie GC, spot migration, rightsizing via ARIA FinOps agent.",
    status: "ACTIVE",
    ariaIntegration: "Core",
    coverage: 82,
    href: "/dashboard/aria",
  },
  {
    id: "S-20",
    name: "Autonomous Remediation / Self-Healing",
    category: "Advanced",
    description: "Five-agent dispatcher gated by HealingMode and blast-radius cap.",
    status: "ACTIVE",
    ariaIntegration: "Core",
    coverage: 94,
    href: "/dashboard/aria",
  },
  {
    id: "S-21",
    name: "Threat Intelligence & Hunting",
    category: "Advanced",
    description: "CISA KEV + NVD + MITRE ATT&CK feed fusion.",
    status: "ACTIVE",
    ariaIntegration: "Medium",
    coverage: 72,
  },
  {
    id: "S-22",
    name: "Compliance-as-a-Service",
    category: "Advanced",
    description: "SOC 2, ISO 27001, PCI, HIPAA, DPDP with append-only evidence.",
    status: "ACTIVE",
    ariaIntegration: "High",
    coverage: 87,
    href: "/dashboard/compliance",
  },
  {
    id: "S-23",
    name: "SBOM & Supply Chain Security",
    category: "Advanced",
    description: "CycloneDX ingest with KEV correlation.",
    status: "ACTIVE",
    ariaIntegration: "Medium",
    coverage: 68,
  },
  {
    id: "S-24",
    name: "Data Privacy & PII Protection",
    category: "Advanced",
    description: "Bedrock PII anonymization guardrail enforced on every LLM call.",
    status: "ACTIVE",
    ariaIntegration: "High",
    coverage: 79,
  },
  {
    id: "S-25",
    name: "Multi-Cloud Security Orchestration",
    category: "Multi-Cloud",
    description: "Unified ARIA event bus across AWS, Azure, and GCP.",
    status: "PARTIAL",
    ariaIntegration: "High",
    coverage: 58,
  },
  {
    id: "S-26",
    name: "Hybrid & Edge Security",
    category: "Multi-Cloud",
    description: "Constrained-environment healing profiles for on-prem and edge.",
    status: "PLANNED",
    ariaIntegration: "Medium",
    coverage: 30,
  },
  {
    id: "S-27",
    name: "Third-Party / Vendor Risk",
    category: "Multi-Cloud",
    description: "Questionnaire-driven risk matrix for supply chain exposure.",
    status: "ACTIVE",
    ariaIntegration: "Low",
    coverage: 81,
  },
  {
    id: "S-28",
    name: "Executive Security Advisory (vCISO)",
    category: "Multi-Cloud",
    description: "Board-ready posture score and trend analytics.",
    status: "ACTIVE",
    ariaIntegration: "Medium",
    coverage: 88,
  },
  {
    id: "S-29",
    name: "Continuous Red Teaming & SLO Monitoring",
    category: "Multi-Cloud",
    description: "SLO breach TAL events feeding the ARIA predictor.",
    status: "ACTIVE",
    ariaIntegration: "High",
    coverage: 75,
  },
];
